### DISCUSSION TITLE
Aligned UI

### DISCUSSION THREAD

**Discussion by trevarj** [osa1/tiny#299] [Show and tell]
Working on an aligned UI. Here is the first working iteration. 
It will be configurable (with preferred max nickname size), and you can fallback to the old style 

Nicks are cut off at 12 chars here.
Not quite sure if the 'activity' messages (join/part/nickchange) should be aligned or leave them as is.  Share your thoughts!
![image](https://user-images.githubusercontent.com/5448324/104086286-9cc1fc80-5267-11eb-9c7e-cfc4e84b91a0.png)

**Comment by osa1** [comment]
Wow.. this looks so good. Thanks for doing this @trevarj!

I like this quite a lot, would be happy to merge and release when ready.

**Comment by trevarj** [comment]
Tracking branch: https://github.com/trevarj/tiny/tree/aligned-ui

**Reply by osa1** [reply]
How do I enable it? I just built it but it's using the current UI by default.

**Reply by trevarj** [reply]
In the default config.yml there are new options:

```
# (Optional) UI Message Layout Style. Defaults to 'compact'
# ui_style: compact
 ui_style:
   aligned:
     # Nicks greater than this value will be truncated
     max_nick_length: 12
```
