### DISCUSSION TITLE
Does a value of DEFAULT in the color specs refer to the terminal's foreground and background colors?

### DISCUSSION THREAD

**Discussion by bound-variable** [osa1/tiny#389] [Q&A] [answered]
For example,

```
colors:
        cursor:
        fg: default
        bg: default
```

Will this invoke the terminal's foreground and background colors, or its cursor colors, or else something else?
