### ISSUE TITLE
/connect command works, but if I copy the same info to .tinyrc.yml can't connect

### ISSUE THREAD

**Issue by osa1** [osa1/tiny#124]
This is really weird. This command works fine:

```
/connect irc.oftc.net:6667
```

But if I add this to .tinyrc.yml:

```
    - addr: irc.oftc.net
      port: 6667
      tls: false
      hostname: omer
      realname: omer
      nicks:
          - 'osa1'
```

I can't connect to this server, I get

```
19:27 Connection error: connection refused. Will try to reconnect in 30 seconds.
Connection error (HUP). Will try to reconnect in 30 seconds.
```

I suspect this is because of some subtle difference between connection parameters between these two methods. It'd be great if these two worked the same way.
