### ISSUE TITLE
tiny fails to connect with "other os error"

### ISSUE THREAD

**Issue by zserik** [osa1/tiny#144]
I configured `tiny`, following the description in the `README.md`, but `tiny` fails to connect to any server (tried servers: `irc.mozilla.org, chat.freenode.net`) with the following message:
```
Connection error: other os error. Will try to reconnect in 30 seconds.
Disconnected. Will try to reconnect in 30 seconds.
```
I don't really know how to debug this.
I tried connecting with either TLS enabled or disabled, both don't work.
Possible related: my network has no outgoing IPv6 routes/internet acces, only IPv4, but uses IPv6 internally.

**Comment by osa1** [comment]
Can you paste your tinyrc.yml file, without the passwords? 

> I tried connecting with either TLS enabled or disabled, both don't work.

Did you update the port after changing TLS settings? For plain TCP port 6665 should work, for TLS you need 6697. 

> Possible related: my network has no outgoing IPv6 routes/internet acces, only IPv4, but uses IPv6 internally.

Interesting. Does this mean you can only connect to IPv4 addresses? Currently we use the first address that the DNS query returns, perhaps in your case that's an IPv6 address that you can't use, but maybe the query returns more addresses (some of which are IPv4). I'm not sure how to reproduce this issue locally, it'd be helpful if you could try printing all addresses here: https://github.com/osa1/tiny/blob/master/libtiny_client/src/lib.rs#L405-L411 Simply adding a line like

```
for other_addr in addr_iter { println!("{:?}", other_addr); }
```

Should do it.

**Comment by zserik** [comment]
1.
```yaml
# Servers to auto-connect
servers:
    - addr: irc.mozilla.org
      port: 6667
      #port: 6697
      #tls: true
      hostname: 'ytrizja.duckdns.org'
      realname: Erik Z
      nicks: [ zseri, zseri2 ]

      # Channels to automatically join
      join:
          - '#rust'

      # Three authentication methods: pass, sasl, and nickserv_ident
      # These are optional and you probably only need one of these, delete
      # others.

      # Server or nick password
      # pass: 'hunter2'

      # SASL authentication
      #sasl:
      #  username: 'tiny_user'
      #  password: 'hunter2'

      # Identify nick by sending a message to NickServ:
      # (useful when `pass` or `sasl` fields above are not used)
      #nickserv_ident: 'hunter2'
    - addr: chat.freenode.net
      port: 6667
      #port: 6697
      #tls: true
      hostname: 'ytrizja.duckdns.org'
      realname: Erik Z
      nicks: [ zseri, zseri2 ]

      join:
          - '#esoteric'

      #sasl:
        #username: 'zseri'
        #password: ''

# Defaults used when connecting to servers via the /connect command
defaults:
    nicks: [ zseri, zseri2 ]
    hostname: 'ytrizja.duckdns.org'
    realname: Erik Z
    join: []
    tls: false

# Where to put log files
log_dir: '/home/z/tiny_logs'

# Color theme based on 256 colors (if supported). Colors can be defined as color
# indices (0-255) or with their names.
#
# Accepted color names are:
# default (0), black (0), maroon (1), green (2), olive (3), navy (4),
# purple (5), teal (6), silver (7), gray (8), red (9), lime (10),
# yellow (11), blue (12), magenta (13), cyan (14), white (15)
#
# Attributes can be combined (e.g [bold, underline]), and valid values are bold
# and underline
colors:
    nick: [ 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14 ]

    clear:
        fg: default
        bg: default

    user_msg:
        fg: black
        bg: default

    err_msg:
        fg: black
        bg: maroon
        attrs: [bold]

    topic:
        fg: cyan
        bg: default
        attrs: [bold]

    cursor:
        fg: black
        bg: default

    join:
        fg: lime
        bg: default
        attrs: [bold]

    part:
        fg: maroon
        bg: default
        attrs: [bold]

    nick_change:
        fg: lime
        bg: default
        attrs: [bold]

    faded:
        fg: 242
        bg: default

    exit_dialogue:
        fg: default
        bg: navy

    highlight:
        fg: red
        bg: default
        attrs: [bold]

    completion:
        fg: 84
        bg: default

    timestamp:
        fg: 242
        bg: default

    tab_active:
        fg: default
        bg: default
        attrs: [bold]

    tab_normal:
        fg: gray
        bg: default

    tab_new_msg:
        fg: purple
        bg: default

    tab_highlight:
        fg: red
        bg: default
        attrs: [bold]

```
2. yes
