### ISSUE TITLE
Tiny panicks when connecting to irc.gitter.im

### ISSUE THREAD

**Issue by Kabouik** [osa1/tiny#211]
Maybe I didn't configure it correctly, but if so I couldn't find what parameter is wrong and causing this issue:

```
thread 'main' panicked at 'byte index 13 is out of bounds of ` 1.10.0`', /rust/47c3158c3d797f75f0f7b2b2a977179668919dab/src/libcore/str/mod.rs:2052:47
```

```
    - addr: irc.gitter.im
      port: 6697
      tls: true
      realname: Kabouik
      nicks: [Kabouik]

      # (optional) Server alias for display in tab line
      alias: Gitter

      # Channels to automatically join
      join:
          - '#jarun/nnn'

      # Server or nick password
      pass: 'mytoken'
```
I tried with or without nicknames listed in `nicks`, with or without the channel, but no difference.

I followed instructions at https://irc.gitter.im/.
