### ISSUE TITLE
Can't connect to irc.rizon.net using rustls

### ISSUE THREAD

**Issue by osa1** [osa1/tiny#215]
Originally reported @Kabouik in #211, if I connect to irc.rizon.net using these settings:

```
servers:
    - addr: irc.rizon.net
      port: 6697
      tls: true
      realname: ...
      nicks: [...]
```

In rustls build I get these errors:

```
Resolving host...
Connecting to 104.199.121.36:6697
10:17 Connection error: received fatal alert: HandshakeFailure
Connecting to 80.65.57.18:6697
Connection error: received fatal alert: HandshakeFailure
Connecting to [2607:f128:22:3133:312:18:313:11b2]:6697
Connection error: Network is unreachable (os error 101)
Connecting to [2001:1ad8:8:6667:5718::]:6697
Connection error: Network is unreachable (os error 101)
Disconnected. Will try to reconnect in 30 seconds.
```

It works if I use native-tls.

I'm not sure if this is a bug or not, perhaps something missing in rustls or an unsupported feature, so opening this issue just to investigate.
