### ISSUE TITLE
Failed to lookup address information on WSL

### ISSUE THREAD

**Issue by LordMZTE** [osa1/tiny#277]
# What happened?
When starting a version of tiny which was compiled with cargo on WSL (reproduced on ArchWSL and UbuntuWSL) the following error occurs
```
Resolving host...
Connection error: failed to lookup address information: Temporary failure in name resolution
```
This issue does not occur on a prebuilt release.
This has been discussed previously in #269 and #276.

I cannot ping the IRC server (100% packet loss) however since it works on the prebuilt versions I'm guessing it's not a network issue.

I was able to get this behaviour on this server
```yaml
servers:
  - addr: "irc.oftc.net"
    port: 6667
    tls: false
    realname: "LordMZTE"
    nicks: ["LordMZTE"]
```
# Suspected Cause
I'm suspecting that I may be using a different OpenSSL version from the one that was used in the prebuild versions.
These are my OpenSSL versions:
## ArchWSL
```sh
$ pacman -Q openssl
openssl 1.1.1.h-1
```
## UbuntuWSL
```sh
$ apt show libssl-dev
Package: libssl-dev
Version: 1.1.1f-1ubuntu2
```
