### ISSUE TITLE
Config setting for sending a message when you join servers

### ISSUE THREAD

**Issue by BanchouBoo** [osa1/tiny#350]
I use some servers that have their own authentication methods that involve messaging a bot.

Something like this:

```yaml
servers:
    - addr: irc.oftc.net
      port: 6697
      tls: true
      realname: yourname
      nicks: [tiny_user]

      join:
          - "#tiny"
      
     # Messages that are sent to the server when you connect
      connect_messages:
          - "message 1"
          - "message 2"
```

**Comment by osa1** [comment]
Do you only need to message to this bot when you first connect, or do you also need to message it when you change your nick?

Just a bit of backstory: years ago tiny had an `auto_cmds` field in config for running commands when we connect to a server. That was quite flexible for the user (you could message to a bot, for example), but it also caused a lot of problems and did not work well in general. Some of the issues are mentioned in [0.4.3 changelog][1]. So I removed it in favor of nickserv_ident and other fields related to identification.

Perhaps another design here could be having commands registered for certain events. For example,

```
servers:
    - addr: irc.oftc.net
      ...

      on_connect:
          - 'msg ...'

      on_nick_change:
          - 'msg ...'
```

Just an idea.

[1]: https://github.com/osa1/tiny/blob/master/CHANGELOG.md#20180901-043
