### ISSUE TITLE
cannot define a keybinding outside of the default ones

### ISSUE THREAD

**Issue by t184256** [osa1/tiny#358]
On 8f4428ee41b46152fd4c2f1abf883a2f1942ceaa, with a `key_map` like

``` yaml
key_map:
    home: input_move_curs_start
    end: input_move_curs_end
    ctrl_n: tab_prev
    ctrl_h: tab_move_left
```

I get `Can't parse TUI config: Message("invalid value: string \"ctrl_h\", expected
single keys: backspace, del, end, esc, home, pgdown, pgup, tab, up, down, left
right, [a-z], [0-9], [f1-f12]. modifiers with an arrow key, function key, or
single characters:  alt, shift, ctrl", Some(Pos { marker: Marker { index: 2702,
line: 135, col: 4 }, path: "key_map" }))`

My suspicions are, I'm unable to set bindings beyond [what's defined in the default config](https://github.com/osa1/tiny/blob/b77c2230bc2ed8b9ffd1ca9c622a0cd0d985cb42/crates/libtiny_tui/src/key_map.rs#L90).
