### ISSUE TITLE
multiple servers with same addr

### ISSUE THREAD

**Issue by eoli3n** [osa1/tiny#374]
I'm using tiny with [soju](https://soju.im/) irc bouncer in [single stream mode](https://git.sr.ht/~emersion/soju/tree/master/doc/getting-started.md#single-upstream-mode).

So I connect to my server two times with, a different login to reach libera or oftc : ``eoli3n/irc.oftc.net`` and ``eoli3n/irc.libera.chat``.
It seems problematic to tiny.
A solution would be to be able to set a ``name`` in tiny config like
```
    - addr: my_server.domain.com
      name: libera
      realname: eoli3n
      nicks:
        - eoli3n
      sasl:
        username: 'eoli3n/irc.libera.chat'

    - addr: my_server.domain.com
      name: oftc
      realname: eoli3n
      nicks:
        - eoli3n
      sasl:
        username: 'eoli3n/irc.oftc.net'
```

**Comment by eoli3n** [comment]
After more test, it works well, but then, tiny concatenate both connection. So I can just join channels for the first one in the ``my_server.domain.com`` tab. Any workaround ?

**Comment by trevarj** [comment]
If you set an alias does it work? I don't think `name` is a config.
e.g
```
- addr: my_server.domain.com
  alias: libera
...
```

**Comment by eoli3n** [comment]
Worked like a charm ! Thanks

**Comment by eoli3n** [comment]
Oh sorry, I mistested
With that config:
```

    - addr: bouncer.fr
      alias: libera
      ...
      sasl:
        username: 'eoli3n/irc.libera.chat'

    - addr: bouncer.fr
      alias: oftc
      ...
      sasl:
        username: 'eoli3n/irc.oftc.net'
```

When I start tiny, I can see a "libera" buffer, but not the "oftc" one.
