### ISSUE TITLE
A sending user's name is invisible when receiving /msg

### ISSUE THREAD

**Issue by Pound-Hash** [osa1/tiny#393]
### The problem
![image](https://user-images.githubusercontent.com/51193876/196541305-3305ab00-3995-4979-ac87-c559acfb541c.png)

As can be seen, when a user mentions me (if that user isn't a mod), I can't see their name.

### My config
```
colors:

    clear:
        fg: black
        bg: white

    user_msg:
        fg: black
        bg: white

    err_msg:
        fg: black
        bg: white
        attrs: [bold]

    topic:
        fg: black
        bg: white
        attrs: [bold]

    cursor:
        fg: black
        bg: white

    join:
        fg: black
        bg: white
        attrs: [bold]

    part:
        fg: black
        bg: white
        attrs: [bold]

    nick_change:
        fg: black
        bg: white
        attrs: [bold]

    faded:
        fg: black
        bg: white

    exit_dialogue:
        fg: black
        bg: white

    highlight:
        fg: black
        bg: white
        attrs: [bold]

    completion:
        fg: black
        bg: white

    timestamp:
        fg: black
        bg: white

    tab_active:
        fg: black
        bg: white
        attrs: [bold]

    tab_normal:
        fg: black
        bg: white

    tab_new_msg:
        fg: black
        bg: white

    tab_highlight:
        fg: black
        bg: white
        attrs: [bold]
```
