### ISSUE TITLE
How to use password command with non-SASL configs

### ISSUE THREAD

**Issue by heywoodlh** [osa1/tiny#406]
I have a Bitlbee instance that I'm just using for myself. I have tried to configure a command to fetch my password to identify with my server but have been unsuccessful doing it.

I have tried using the "command" parameter with the nickserv_ident and pass config options but tiny complains about invalid values in the config file.

Is there a way to use the command parameter with nickserv_ident or pass? If so, could someone provide a snippet? Because I haven't been able to figure it out.

Thanks!

**Comment by osa1** [comment]
I have this in my config:

```yaml
servers:
    - addr: irc.oftc.net
      port: 6697
      tls: true
      nicks: [...]
      nickserv_ident:
        command: 'pass show oftc_nickserv'
```

Does this not work for you? If not could you share your config with the important bits censored?
