### ISSUE TITLE
`pass` command fails if it has other info other than the password

### ISSUE THREAD

**Issue by uncomfyhalomacro** [osa1/tiny#413]
How to reproduce:
1. `pass generate mycooluser`
2. Create account for `mycooluser`
3. `pass edit mycooluser` and then add some stuff in the next line after the password e.g. your username field
4. Use this to your config
```yaml
nicks: [mycooluser]
  nickserv_ident:
    command: 'pass show mycooluser'
```
5. Fails to login because incorrect password

How to resolve:
Delete everything except the password.
