### ISSUE TITLE
How to set "ignore" mode automatically upon login?

### ISSUE THREAD

**Issue by wrycode** [osa1/tiny#68]
[Probably low priority]

adding 
 - '/ignore'
to auto_cmds throws a 

> Can't parse config file:
while parsing a block mapping, did not find expected key at line 21 column 1

error. I'm unsure of how to correctly escape the "/" in yaml. I am also unsure if auto_cmds supports tiny commands, or only commands(messages) issued to the irc server.

If the latter is true, as is implied by the format of the example auto_cmds given, it would be nice to set ignore mode automatically for a server.

**Comment by meain** [comment]
@wrycode Just add `ignore` without the slash in auto_cmds. You don't have to use `/` when using auto_cmds.

**Comment by wrycode** [comment]
Thanks @meain, but this still isn't working for me. In my VM with a fresh install of Tiny, I added the line:

          - 'ignore'

And I'm still getting the error

> while parsing a block mapping, did not find expected key at line 11 column 1

I tried `ignore` without the single quotes and got the same error, and Tiny does not start.

**Comment by meain** [comment]
@wrycode 

This works for me :
```yaml
    - addr: irc.freenode.net
      port: 6667
      hostname: plank
      realname: Abin Simon
      nicks: [meain]
      auto_cmds:
          - 'nick meain'
          - 'msg NickServ identify not_my_pass'
          - 'ignore'
```

If you don't mind could you post your config file
